package httpserver

import (
	"fmt"
	"log/slog"
	"net/http"
	"strings"

	"github.com/al-bashkir/openvpn-keycloak-auth/internal/logsanitize"
	"github.com/al-bashkir/openvpn-keycloak-auth/internal/oidc"
	"github.com/al-bashkir/openvpn-keycloak-auth/internal/openvpn"
	"github.com/al-bashkir/openvpn-keycloak-auth/internal/session"
)

// handleAuthRedirect handles short auth redirect URLs.
// OpenVPN's auth_pending_file has a 256-char line limit (OPTION_LINE_SIZE).
// Full OIDC auth URLs with PKCE parameters exceed this limit.
// This endpoint serves a short URL (e.g., /auth/<state>) that 302-redirects
// to the full Keycloak authorization URL stored in the session.
func (s *Server) handleAuthRedirect(w http.ResponseWriter, r *http.Request) {
	// Extract state from URL path: /auth/{state}
	_, state, ok := splitAuthPath(r.URL.Path)
	if !ok || state == "" {
		s.renderError(w, "Invalid auth URL")
		return
	}

	// Look up session by state
	sess, err := s.sessionMgr.GetByState(state)
	if err != nil {
		slog.Error("auth redirect: session not found", // #nosec G706 -- no externally controlled values logged
			"error", err,
		)
		s.renderError(w, "Session not found or expired. Please try connecting again.")
		return
	}

	if sess.AuthURL == "" {
		slog.Error("auth redirect: no auth URL in session", // #nosec G706 -- session.ID is crypto/rand hex
			"session_id", sess.ID,
		)
		s.renderError(w, "Authentication flow not initialized. Please try connecting again.")
		return
	}

	slog.Debug("auth redirect", // #nosec G706 -- session.ID is crypto/rand hex
		"session_id", sess.ID,
	)

	// #nosec G710 -- sess.AuthURL is server-generated by oauth2.AuthCodeURL
	// (issuer host from validated config + crypto/rand params); it is not
	// derived from request input, so this is not an open redirect.
	http.Redirect(w, r, sess.AuthURL, http.StatusFound)
}

// handleCallback handles OIDC callback requests.
// This completes the OAuth2 authorization code flow:
// 1. Extract code and state from query parameters
// 2. Look up session by state
// 3. Exchange code for tokens (with PKCE)
// 4. Verify ID token and extract claims
// 5. Validate username (if required)
// 6. Write success/failure to OpenVPN control file
func (s *Server) handleCallback(w http.ResponseWriter, r *http.Request) {
	// Extract callback parameters
	code := r.URL.Query().Get("code")
	state := r.URL.Query().Get("state")
	errorParam := r.URL.Query().Get("error")
	errorDesc := r.URL.Query().Get("error_description")

	slog.Info("callback received", // #nosec G706 -- only boolean values logged, no injection risk
		"code_present", code != "",
		"state_present", state != "",
		"error_present", errorParam != "",
	)

	// Handle OIDC error responses
	if errorParam != "" {
		slog.Error("OIDC error in callback", // #nosec G706 -- raw provider-controlled details intentionally omitted
			"error_code", safeOAuthErrorCode(errorParam),
			"description_present", errorDesc != "",
		)
		const failureReason = "OIDC authentication failed"
		const browserMessage = "Authentication failed. Please try again."

		// Write auth failure immediately so OpenVPN doesn't hang until timeout
		if state != "" && s.sessionMgr != nil {
			if sess, err := s.sessionMgr.GetByState(state); err == nil {
				slog.Info("writing auth failure for OIDC error", // #nosec G706 -- session.ID is crypto/rand hex
					"session_id", sess.ID,
					"error_code", safeOAuthErrorCode(errorParam),
				)
				s.writeAuthFailure(sess, failureReason)
			}
		}

		s.renderError(w, browserMessage)
		return
	}

	// Validate parameters
	if code == "" || state == "" {
		slog.Error("invalid callback parameters", // #nosec G706 -- only boolean values logged, no injection risk
			"code_present", code != "",
			"state_present", state != "",
		)
		if state != "" && s.sessionMgr != nil {
			if sess, err := s.sessionMgr.GetByState(state); err == nil {
				s.writeAuthFailure(sess, "Invalid callback parameters")
			}
		}
		s.renderError(w, "Invalid callback parameters")
		return
	}

	// Look up session by state
	session, err := s.sessionMgr.GetByState(state)
	if err != nil {
		slog.Error("session not found", // #nosec G706 -- raw state intentionally omitted
			"error", err,
		)
		s.renderError(w, "Session not found or expired. Please try connecting again.")
		return
	}

	// Ensure we always write a result (safety net).
	// Only deletes the session if the auth_control_file write succeeds.
	defer func() {
		if s.sessionMgr == nil {
			return
		}

		if ok := s.sessionMgr.ClaimResultWrite(session.ID); !ok {
			return
		}

		slog.Error("callback completed without writing result, writing failure",
			"session_id", session.ID,
		)

		if err := openvpn.WriteAuthFailure(
			session.AuthControlFile,
			session.AuthFailedReasonFile,
			"Internal error",
		); err != nil {
			s.sessionMgr.ReleaseResultWriteClaim(session.ID)
			slog.Error("failed to write safety-net auth failure",
				"session_id", session.ID,
				"error", err,
			)
			// Keep session for cleanup/retry attempts.
			return
		}

		_ = s.sessionMgr.MarkResultWritten(session.ID)
		s.sessionMgr.Delete(session.ID)
	}()

	// Exchange code for tokens (also verifies id_token nonce binding)
	claims, err := s.oidcProvider.ExchangeCode(r.Context(), code, session.CodeVerifier, session.Nonce)
	if err != nil {
		slog.Error("token exchange failed", // #nosec G706 -- raw provider-controlled error details intentionally omitted
			"session_id", session.ID,
			"error_category", "token_exchange_failed",
		)
		s.writeAuthFailure(session, "Token exchange failed")
		s.renderError(w, "Authentication failed. Please try again.")
		return
	}

	// Validate token claims against username and role policy
	if validationErr := oidc.Validate(s.cfg, claims, session.Username); validationErr != nil {
		slog.Error("token validation failed", // #nosec G706 -- raw token-controlled claim values intentionally omitted
			"session_id", session.ID,
			"error_category", validationFailureCategory(validationErr),
		)
		s.writeAuthFailure(session, "Token validation failed")
		s.renderError(w, "Authentication failed. Please contact your VPN administrator.")
		return
	}

	// Extract username for logging (already validated unless AllowUsernameMismatch is set)
	username, _ := claims[s.cfg.Auth.UsernameClaim].(string)

	slog.Info("user authenticated successfully", // #nosec G706 -- values sanitized via logsanitize.Sanitize
		"session_id", session.ID,
		"username", logsanitize.Sanitize(username),
		"expected_username", logsanitize.Sanitize(session.Username),
		"ip", logsanitize.Sanitize(session.UntrustedIP),
	)

	// Authentication successful!
	if err := s.writeAuthSuccess(session); err != nil {
		s.renderError(w, "Authentication succeeded, but the VPN server could not be notified. Please try connecting again.")
		return
	}

	s.renderSuccess(w, "You are now connected to the VPN. You may close this window.")
}

// writeAuthSuccess writes success to the OpenVPN control file and deletes the session.
func (s *Server) writeAuthSuccess(sess *session.Session) error {
	if s.sessionMgr == nil {
		return fmt.Errorf("session manager is nil")
	}

	if ok := s.sessionMgr.ClaimResultWrite(sess.ID); !ok {
		slog.Warn("session already completed, skipping auth success write",
			"session_id", sess.ID,
		)
		return nil
	}

	if err := openvpn.WriteAuthSuccess(sess.AuthControlFile); err != nil {
		s.sessionMgr.ReleaseResultWriteClaim(sess.ID)
		slog.Error("failed to write auth success",
			"session_id", sess.ID,
			"error", err,
		)
		return err
	}

	slog.Info("auth success written",
		"session_id", sess.ID,
		"username", logsanitize.Sanitize(sess.Username),
		"ip", logsanitize.Sanitize(sess.UntrustedIP),
	)

	_ = s.sessionMgr.MarkResultWritten(sess.ID)
	s.sessionMgr.Delete(sess.ID)
	return nil
}

// writeAuthFailure writes failure to the OpenVPN control file and deletes the session.
func (s *Server) writeAuthFailure(sess *session.Session, reason string) {
	if s.sessionMgr == nil {
		slog.Error("session manager is nil, cannot write auth failure", // #nosec G706 -- values sanitized via logsanitize.Sanitize
			"session_id", sess.ID,
			"reason", logsanitize.Sanitize(reason),
		)
		return
	}

	if ok := s.sessionMgr.ClaimResultWrite(sess.ID); !ok {
		slog.Warn("session already completed, skipping auth failure write", // #nosec G706 -- session.ID is crypto/rand hex
			"session_id", sess.ID,
		)
		return
	}

	if err := openvpn.WriteAuthFailure(
		sess.AuthControlFile,
		sess.AuthFailedReasonFile,
		reason,
	); err != nil {
		s.sessionMgr.ReleaseResultWriteClaim(sess.ID)
		slog.Error("failed to write auth failure", // #nosec G706 -- session.ID is crypto/rand hex; err is internal
			"session_id", sess.ID,
			"error", err,
		)
		// Keep session for cleanup/retry attempts.
		return
	}

	slog.Info("auth failure written", // #nosec G706 -- values sanitized via logsanitize.Sanitize
		"session_id", sess.ID,
		"username", logsanitize.Sanitize(sess.Username),
		"reason", logsanitize.Sanitize(reason),
	)

	_ = s.sessionMgr.MarkResultWritten(sess.ID)
	s.sessionMgr.Delete(sess.ID)
}

func safeOAuthErrorCode(errorCode string) string {
	switch errorCode {
	case "invalid_request", "unauthorized_client", "access_denied", "unsupported_response_type", "invalid_scope", "server_error", "temporarily_unavailable", "login_required", "interaction_required", "consent_required", "account_selection_required":
		return errorCode
	default:
		return "other"
	}
}

func validationFailureCategory(err error) string {
	if err == nil {
		return "none"
	}

	errText := strings.ToLower(err.Error())
	switch {
	case strings.Contains(errText, "username claim"):
		return "username_claim_missing"
	case strings.Contains(errText, "username mismatch"):
		return "username_mismatch"
	case strings.Contains(errText, "failed to extract roles"):
		return "role_claim_missing"
	case strings.Contains(errText, "required roles"):
		return "required_role_missing"
	default:
		return "token_validation_failed"
	}
}

// splitAuthPath splits a request path at its "/auth/" segment, returning the
// prefix before it and the state after it. ok is false when the path is not a
// short auth link.
func splitAuthPath(p string) (prefix, state string, ok bool) {
	idx := strings.LastIndex(p, "/auth/")
	if idx == -1 {
		return "", "", false
	}
	return p[:idx], p[idx+len("/auth/"):], true
}
